#!/bin/sh

case "$1" in
  start)
        printf "Starting SystemInfo server. "
        /usr/bin/python3 /usr/bin/systeminfo.py &
        echo "OK"
        ;;
  stop)
        printf "Stopping SystemInfo server. "
        killall python3 2>/dev/null
        echo "OK"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
